import type { Metadata } from "next";
import { getToolBySlug, getRelatedTools } from "@/lib/tools/registry";
import ToolPageLayout from "@/components/layout/ToolPageLayout";
import QrCodeGeneratorTool from "@/components/tool-ui/QrCodeGeneratorTool";

const SLUG = "qr-code-generator";

export const metadata: Metadata = {
  title: "QR Code Generator – Create QR Codes Free Online",
  description:
    "Generate QR codes from any URL, text, email, or phone number instantly. Download as PNG. Free online QR code generator, no signup required.",
  alternates: { canonical: "https://www.aikittools.com/qr-code-generator" },
  openGraph: {
    title: "QR Code Generator – Create QR Codes Free Online",
    description:
      "Generate QR codes from any URL, text, email, or phone number instantly. Download as PNG. Free online QR code generator, no signup required.",
    url: "https://www.aikittools.com/qr-code-generator",
    siteName: "AI Kit Tools",
    type: "website",
  },
  robots: { index: true, follow: true },
};

const seoSections = [
  {
    heading: "What is the QR Code Generator?",
    body: "The QR Code Generator turns any text, URL, email address, or phone number into a downloadable QR code image in real time. QR codes are everywhere now — restaurant menus, product packaging, business cards, event check-ins, and marketing print materials all use them to bridge physical and digital experiences. Instead of expecting someone to type a long URL, a QR code lets anyone with a smartphone camera jump directly to your link in seconds. This tool generates clean, high-contrast QR codes that scan reliably on any device, and lets you download them as PNG images ready for any project.",
  },
  {
    heading: "How to Use This Tool",
    body: [
      "Type or paste your URL, text, email, or phone number into the input field.",
      "The QR code preview updates automatically as you type.",
      "Adjust the size using the slider if you need a larger or smaller output.",
      "Review the preview to confirm it looks clean and correct.",
      "Click Download PNG to save the image to your device.",
    ],
  },
  {
    heading: "Why Use QR Code Generator Online?",
    body: "Free and instant — no account, no watermarks, no limits on how many QR codes you generate. Everything runs in your browser, so codes appear immediately without any server calls. Download and use them in print, digital, or wherever you need them, with no restrictions. The PNG files are high quality, suitable for both screen display and printing at reasonable sizes.",
  },
];

const faqs = [
  {
    question: "What types of data can I encode in a QR code?",
    answer:
      "You can encode URLs, plain text, email addresses, phone numbers, SMS messages, Wi-Fi credentials, vCard contact data, and more. Our generator supports any text input.",
  },
  {
    question: "Are QR codes generated here permanent?",
    answer:
      "Yes. QR codes generated by this tool are static and permanent. The encoded data is baked directly into the image, so they will always decode to the same content regardless of whether this website exists. Unlike dynamic QR codes from paid services, our codes have no expiration.",
  },
  {
    question: "What image format is the QR code downloaded in?",
    answer:
      "The QR code is downloaded as a PNG file, which is a lossless format suitable for both digital use and high-quality printing.",
  },
  {
    question: "Is there a limit on how much text I can encode?",
    answer:
      "QR codes have a data capacity limit. For URLs and short text, you won't hit this limit. If you try to encode very long text (thousands of characters), the QR code may become very dense and harder to scan. For URLs, consider using a URL shortener first.",
  },
];

export default function QrCodeGeneratorPage() {
  const tool = getToolBySlug(SLUG)!;
  const relatedTools = getRelatedTools(SLUG);

  return (
    <ToolPageLayout tool={tool} relatedTools={relatedTools} faqs={faqs} seoSections={seoSections}>
      <QrCodeGeneratorTool />
    </ToolPageLayout>
  );
}
