import type { Metadata } from "next";
import { getToolBySlug, getRelatedTools } from "@/lib/tools/registry";
import ToolPageLayout from "@/components/layout/ToolPageLayout";
import QrCodeGeneratorTool from "@/components/tool-ui/QrCodeGeneratorTool";

const SLUG = "qr-code-generator";

export const metadata: Metadata = {
  title: "QR Code Generator – Create & Download QR Codes Free",
  description:
    "Generate a QR code from any URL, text, or link in seconds. Download as PNG for print or digital use. Free, no signup, no watermark, no limits.",
  alternates: {
    canonical: "https://www.aikittools.com/qr-code-generator",
    languages: {
      "en-US": "https://www.aikittools.com/qr-code-generator",
    },
  },
  openGraph: {
    title: "QR Code Generator – Create QR Codes Free Online",
    description:
      "Generate QR codes from any URL, text, email, or phone number instantly. Download as PNG. Free online QR code generator, no signup required.",
    url: "https://www.aikittools.com/qr-code-generator",
    siteName: "AI Kit Tools",
    type: "website",
  },
  robots: { index: true, follow: true },
};

const seoSections = [
  {
    heading: "What is the QR Code Generator?",
    body: "The QR Code Generator is a QR code generator for URL, text, email address, or phone number input that creates a downloadable image in real time. QR codes are everywhere now — restaurant menus, product packaging, and teams that create QR code for business card sharing all use them to bridge physical and digital experiences. Instead of expecting someone to type a long URL, a QR code lets anyone with a smartphone camera jump directly to your link in seconds, including a QR code for WhatsApp link campaigns. This tool generates clean, high-contrast QR codes that scan reliably on any device, and lets you generate QR code and download PNG files ready for any project.",
  },
  {
    heading: "How to Use This Tool",
    body: [
      "Type or paste your URL, text, email, or phone number into the input field.",
      "The QR code preview updates automatically as you type.",
      "Adjust the size using the slider if you need a larger or smaller output.",
      "Review the preview to confirm it looks clean and correct.",
      "Click Download PNG to save the image to your device.",
    ],
  },
  {
    heading: "Why Use QR Code Generator Online?",
    body: "Free and instant — this is a free QR code maker no watermark, with no account and no limits on how many QR codes you generate. Everything runs in your browser, so codes appear immediately without any server calls. Download and use them in print, digital, or wherever you need them, with no restrictions. The PNG files are high quality, suitable for both screen display and printing at reasonable sizes.",
  },
];

const faqs = [
  {
    question: "What types of data can I encode in a QR code?",
    answer:
      "You can encode URLs, plain text, email addresses, phone numbers, SMS messages, Wi-Fi credentials, vCard contact data, and more. Our generator supports any text input.",
  },
  {
    question: "Are QR codes generated here permanent?",
    answer:
      "Yes. QR codes generated by this tool are static and permanent. The encoded data is baked directly into the image, so they will always decode to the same content regardless of whether this website exists. Unlike dynamic QR codes from paid services, our codes have no expiration.",
  },
  {
    question: "What image format is the QR code downloaded in?",
    answer:
      "The QR code is downloaded as a PNG file, which is a lossless format suitable for both digital use and high-quality printing.",
  },
  {
    question: "Is there a limit on how much text I can encode?",
    answer:
      "QR codes have a data capacity limit. For URLs and short text, you won't hit this limit. If you try to encode very long text (thousands of characters), the QR code may become very dense and harder to scan. For URLs, consider using a URL shortener first.",
  },
  {
    question: "Can I create a QR code for my WhatsApp number or business card?",
    answer:
      "Yes. For WhatsApp, enter your number in international format as a URL: https://wa.me/923001234567 — scanning the QR code will open a WhatsApp chat directly. For business cards, you can encode your name, phone, email, and website as a vCard text block and the QR code will save it as a contact when scanned.",
  },
  {
    question: "Will the QR code have a watermark or branding on it?",
    answer:
      "No. Every QR code generated by this tool is completely clean with no watermarks, logos, or branding added. The downloaded PNG is yours to use freely in any print or digital project without any restrictions or attribution required.",
  },
];

export default function QrCodeGeneratorPage() {
  const tool = getToolBySlug(SLUG)!;
  const relatedTools = getRelatedTools(SLUG);

  return (
    <ToolPageLayout tool={tool} relatedTools={relatedTools} faqs={faqs} seoSections={seoSections}>
      <QrCodeGeneratorTool />
    </ToolPageLayout>
  );
}
