import type { Metadata } from "next";
import { buildMetadata } from "@/lib/utils/metadata";
import { getToolBySlug, getRelatedTools } from "@/lib/tools/registry";
import ToolPageLayout from "@/components/layout/ToolPageLayout";
import QrCodeGeneratorTool from "@/components/tool-ui/QrCodeGeneratorTool";

const SLUG = "qr-code-generator";

export const metadata: Metadata = buildMetadata({
  title: "Free QR Code Generator Online – Create QR Codes Instantly",
  description:
    "Generate QR codes from any URL, text, email, or phone number. Free online QR code generator with download support. No signup needed.",
  keywords: [
    "qr code generator",
    "free qr code",
    "create qr code online",
    "qr code maker",
    "url to qr code",
    "qr code download",
  ],
  slug: SLUG,
});

const seoSections = [
  {
    heading: "What Is a QR Code Generator?",
    body: "A QR code generator is an online tool that converts any text, URL, phone number, email address, or other data into a scannable QR code image. QR codes (Quick Response codes) are two-dimensional barcodes that can be scanned by any smartphone camera to instantly open a link, display a message, or trigger an action.",
  },
  {
    heading: "How to Use the QR Code Generator",
    body: [
      "Enter a URL, text, email, or phone number in the input field.",
      "Optionally adjust the QR code size using the size slider.",
      "Click 'Generate QR Code' to create the QR code.",
      "A preview of the QR code will appear on the right.",
      "Click 'Download PNG' to save the QR code image to your device.",
    ],
  },
  {
    heading: "Features",
    body: [
      "Supports any text input: URLs, emails, phone numbers, plain text.",
      "Adjustable size from 128×128 to 512×512 pixels.",
      "High error correction for reliable scanning.",
      "Download QR code as a PNG image.",
      "Works entirely in your browser.",
      "Free and unlimited use.",
    ],
  },
  {
    heading: "Common Uses for QR Codes",
    body: [
      "Linking physical products to a website or landing page.",
      "Sharing Wi-Fi credentials without typing.",
      "Adding contact information to business cards.",
      "Directing customers to a menu, app, or payment link.",
      "Encoding event tickets or access codes.",
      "Marketing campaigns and print materials.",
    ],
  },
  {
    heading: "How to Scan a QR Code",
    body: "To scan a QR code, simply open your smartphone's camera app and point it at the QR code. Most modern iOS and Android devices will automatically detect the QR code and display a notification with the encoded link or data. On some devices you may need to use a dedicated QR code scanner app.",
  },
];

const faqs = [
  {
    question: "What types of data can I encode in a QR code?",
    answer:
      "You can encode URLs, plain text, email addresses, phone numbers, SMS messages, Wi-Fi credentials, vCard contact data, and more. Our generator supports any text input.",
  },
  {
    question: "Are QR codes generated here permanent?",
    answer:
      "Yes. QR codes generated by this tool are static and permanent. The encoded data is baked directly into the image, so they will always decode to the same content regardless of whether this website exists. Unlike dynamic QR codes from paid services, our codes have no expiration.",
  },
  {
    question: "What image format is the QR code downloaded in?",
    answer:
      "The QR code is downloaded as a PNG file, which is a lossless format suitable for both digital use and high-quality printing.",
  },
  {
    question: "Is there a limit on how much text I can encode?",
    answer:
      "QR codes have a data capacity limit. For URLs and short text, you won't hit this limit. If you try to encode very long text (thousands of characters), the QR code may become very dense and harder to scan. For URLs, consider using a URL shortener first.",
  },
];

export default function QrCodeGeneratorPage() {
  const tool = getToolBySlug(SLUG)!;
  const relatedTools = getRelatedTools(SLUG);

  return (
    <ToolPageLayout tool={tool} relatedTools={relatedTools} faqs={faqs} seoSections={seoSections}>
      <QrCodeGeneratorTool />
    </ToolPageLayout>
  );
}
