import type { Metadata } from "next";
import { buildMetadata } from "@/lib/utils/metadata";

export const metadata: Metadata = buildMetadata({
  title: "Terms of Service – AI Kit Tools",
  description:
    "Read the AI Kit Tools terms of service. By using our free online tools you agree to these terms.",
  keywords: ["terms of service", "aikittools terms"],
  slug: "terms",
});

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      <h1 className="text-3xl font-bold text-gray-900 mb-2">Terms of Service</h1>
      <p className="text-sm text-gray-400 mb-8">Last updated: April 28, 2026</p>

      <div className="prose prose-gray max-w-none space-y-6 text-gray-600">
        <p className="leading-relaxed">
          By accessing or using <strong className="text-gray-900">AI Kit Tools</strong>{" "}
          (aikittools.com), you agree to be bound by these Terms of Service. If you do not agree,
          please do not use our services.
        </p>

        <h2 className="text-xl font-bold text-gray-900 mt-8">1. Use of Service</h2>
        <p className="leading-relaxed">
          AI Kit Tools provides free online utility tools for personal and professional use. You
          agree to use the service only for lawful purposes. You must not:
        </p>
        <ul className="space-y-1 list-disc list-inside">
          <li>Use the service to process illegal, harmful, or offensive content.</li>
          <li>Attempt to reverse engineer, copy, or resell the service.</li>
          <li>Use automated scraping or bots to excessively consume server resources.</li>
          <li>Use the AI tools to generate misleading, harmful, or deceptive content.</li>
        </ul>

        <h2 className="text-xl font-bold text-gray-900 mt-8">2. Intellectual Property</h2>
        <p className="leading-relaxed">
          The AI Kit Tools name, logo, and website design are the intellectual property of AI Kit
          Tools. Tool outputs generated by your input (e.g., formatted JSON, encoded strings,
          summaries) belong to you.
        </p>

        <h2 className="text-xl font-bold text-gray-900 mt-8">3. Disclaimer of Warranties</h2>
        <p className="leading-relaxed">
          The service is provided &quot;as is&quot; without warranties of any kind. We do not guarantee that
          the tools will always be available, accurate, or error-free. AI-generated summaries may
          contain inaccuracies. Always verify critical outputs.
        </p>

        <h2 className="text-xl font-bold text-gray-900 mt-8">4. Limitation of Liability</h2>
        <p className="leading-relaxed">
          To the maximum extent permitted by law, AI Kit Tools shall not be liable for any indirect,
          incidental, special, or consequential damages arising from your use of the service.
        </p>

        <h2 className="text-xl font-bold text-gray-900 mt-8">5. Third-Party Services</h2>
        <p className="leading-relaxed">
          The AI Text Summarizer uses the OpenAI API. By using that tool, you also agree to be
          bound by{" "}
          <a
            href="https://openai.com/policies/usage-policies"
            target="_blank"
            rel="noopener noreferrer"
            className="text-blue-600 hover:text-blue-800"
          >
            OpenAI&apos;s usage policies
          </a>
          .
        </p>

        <h2 className="text-xl font-bold text-gray-900 mt-8">6. Changes to Terms</h2>
        <p className="leading-relaxed">
          We reserve the right to modify these terms at any time. Continued use of the service
          after changes constitutes your acceptance of the updated terms.
        </p>

        <h2 className="text-xl font-bold text-gray-900 mt-8">7. Governing Law</h2>
        <p className="leading-relaxed">
          These terms are governed by applicable law. Any disputes shall be handled in good faith
          and may be escalated to arbitration if necessary.
        </p>

        <h2 className="text-xl font-bold text-gray-900 mt-8">8. Contact</h2>
        <p className="leading-relaxed">
          Questions about these terms? Contact us at{" "}
          <a href="mailto:m.waqar.ahmed@gmail.com" className="text-blue-600 hover:text-blue-800">
            m.waqar.ahmed@gmail.com
          </a>
          .
        </p>
      </div>
    </div>
  );
}
